-- Добавляем новые поля для способов оплаты и возможностей
ALTER TABLE services 
ADD COLUMN IF NOT EXISTS accepts_apple_pay BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS accepts_google_pay BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS card_reissue BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS high_payment_approval BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS crypto_support BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS sepa_iban BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ach_usd BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS swift BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS supported_currencies TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS billing_regions TEXT[] DEFAULT '{}';